### ISSUE TITLE
Write documentation for the entire project

### ISSUE THREAD

**Issue by PancakeTAS** [p2r3/epochtal#1]
List of files without proper documentation (as of [commit 4f296c2](https://github.com/p2r3/epochtal/commit/4f296c2a65590765327c8108a5f2a367f4f45653)):
- [x] api/archive.js
- [x] api/auth.js
- [x] api/config.js
- [x] api/leaderboard.js
- [x] api/lobbies.js
- [x] api/proof.js
- [x] api/users.js
- [x] api/votes.js
- [x] api/workshopper.js
- [x] defaults/portal2/cfg/epochtal_category.cfg
- [x] defaults/portal2/cfg/valve.rc
- [x] defaults/portal2/scripts/vscripts/debug_scripts/noclip_door_open_sensor.nut
- [x] defaults/portal2/scripts/vscripts/transitions/sp_transition_list.nut
- [x] defaults/portal2/scripts/vscripts/mapspawn.nut
- [x] defaults/portal2/main.js
- [x] pages/live/lobby.js
- [x] pages/live/main.js
- [x] pages/profiles/main.js
- [x] pages/main.js
- [x] pages/tools.js
- [x] routines/epochtal.js
- [x] util/archive.js
- [x] util/avatar.js
- [x] util/categories.js
- [x] util/config.js
- [x] util/coopifier.js
- [x] util/curator.js
- [x] util/demo.js
- [x] util/discord.js
- [x] util/error.js
- [x] util/events.js
- [x] util/flush.js
- [x] util/gamefiles.js
- [x] util/help.js
- [x] util/leaderboard.js
- [x] util/lobbies.js
- [x] util/points.js
- [x] util/print.js
- [x] util/profiledata.js
- [x] util/profilelog.js
- [x] util/proof.js
- [x] util/routine.js
- [x] util/spplice.js
- [x] util/system.js
- [x] util/testcvar.js
- [x] util/tmppath.js
- [x] util/users.js
- [x] util/votes.js
- [x] util/weeklog.js
- [x] util/workshopper.js
- [x] main.js
- [x] steamauth.js

**Comment by PancakeTAS** [comment]
I went through all files again, tried to fix some inconsistencies and also removed quite a bit of documentation that was either completely obvious or redundant for a specific block.
I added a `CONTRIBUTING.md` file to make sure that in the future we can sort of keep it consistent, though I need some feedback from @p2r3 and @soni801 on whether the guidelines I went with are appropriate.

**Comment by soni801** [comment]
I'm just doing the easiest ones first lol, will continue to mention the issue in my commits so it's easier for you to update the task list

**Comment by PancakeTAS** [comment]
mark them off yourself you lazy-

**Comment by soni801** [comment]
I did not know i could do that on someone elses issue lol

**Comment by PancakeTAS** [comment]
@soni801 please never ever link them in your commit message again, lmfao

**Comment by soni801** [comment]
lmaoooooo thats too funny
