### ISSUE TITLE
Change menu background textures

### ISSUE THREAD

**Issue by p2r3** [p2r3/epochtal#11]
Currently, the menu background texture from which the menu fades in is the act 1 background from the singleplayer campaign. This causes a very awkward effect when the act 1 image fades into the dots animation. This texture needs to be found and changed to full black.

**Comment by rudkoLA** [comment]
the textures are at materials/vgui/backgrounds/background01.vtf and materials/vgui/backgrounds/background01_widescreen.vtf inside of pak01
