### ISSUE TITLE
Discord messages should indicate that a run is recorded in segments

### ISSUE THREAD

**Issue by Gewi413** [p2r3/epochtal#123]
Proposed new message
>  📉 Rattlé submitted a new run to "Least Portals" with a segmented time of 1:58.633 (2 portals) in 1st place.

Related: #25

**Comment by p2r3** [comment]
1. I propose the message instead be `... submitted a new segmented run to...`
2. Implementation for this should be a matter of just checking for the `segmented` flag and writing a ternary.
