### ISSUE TITLE
2 smol visual bugs

### ISSUE THREAD

**Issue by Rubix44** [p2r3/epochtal#17]
Two very small visual bugs,

1. When holding and dragging the upvote/downvote buttons it shows the wrong symbol in the wrong color.
2. When deleting a submission and then clicking the delete button again before the leaderboards get updated, the little pop up text follows you around until you update it.

https://github.com/user-attachments/assets/b272fa86-9716-43ba-a4f6-994e02fd015a

https://github.com/user-attachments/assets/e439fa59-1259-451a-b4dc-99999518aecd

**Comment by p2r3** [comment]
Thanks for submitting these! Next time, however, please split these up into separate issues.

**Comment by ArcherTheReal** [comment]
Ill take a look at these in a bit, should i also fix the first one?

**Comment by p2r3** [comment]
@ArcherTheReal The first one can only be partly fixed. The upvote/downvote icons are the same image rotated by a CSS `transform`, so fixing the icon flipping around when dragged isn't possible without loading a whole extra file.

As for the color switching, during development, the colors were flipped, so there's a `hue-rotate(180deg)` somewhere in the CSS. I suppose inverting the color of the source image and removing this hue rotation _would_ fix it for one of the icons, but not the other, as that still has a hue rotation applied anyway.

Realistically, I do not think it matters enough to warrant a fix. Why the hell would anyone care that the upvote button looks different when dragged? Drag behavior is browser-specific, anyway.

**Comment by ArcherTheReal** [comment]
Yeah ik about the first one being 1 icon thats flipped, i just asked cause i dont want to do photo editing :(

**Comment by p2r3** [comment]
The second bug was fixed by #44, the first one doesn't warrant a fix due to reasons mentioned in the discussion above.
