### ISSUE TITLE
Better discord announcements

### ISSUE THREAD

**Issue by Gewi413** [p2r3/epochtal#25]
Some categories need different requirements as to how scores are announced:
- Co-op should display both participants
- meme cat and other non-scored categories don't need a place number
- in general different categories can't be discerned all too well

Proposed fix: each category could have a template string

**Comment by p2r3** [comment]
I doubt the proposed fix is a great option, as that would require adding highly verbose yet purely cosmetic data to the category list of `week.json`, which would repeat for many categories.

Instead, it's probably best to write the function which generates these updates to consider the already existing category data properties, like the `points` or `coop` flags. Essentially, I'm saying that the solution is to add just a couple more "if" statements. To tackle the issue of differentiability, a combination of these flags could be used for assigning a symbol, color, or emoji to the message.
