### ISSUE TITLE
Favicon missing on frontend

### ISSUE THREAD

**Issue by PancakeTAS** [p2r3/epochtal#27]
![image](https://github.com/user-attachments/assets/1750a79c-9d9f-4c52-874c-62adbfe4e2b7)

**Comment by ArcherTheReal** [comment]
What is epochtals favicon? is it just the p2r3 channel logo?

**Comment by p2r3** [comment]
@ArcherTheReal No, I don't own the tournament. It would be the same icon as is used for the Discord server and bot.

**Comment by ArcherTheReal** [comment]
ill add this rq
should i make the icon round or a square will do?

**Comment by p2r3** [comment]
@ArcherTheReal I imagine a square would look awful, so round it is.

**Comment by p2r3** [comment]
Fixed in #37
