### ISSUE TITLE
Progressbar for curation

### ISSUE THREAD

**Issue by ArcherTheReal** [p2r3/epochtal#71]
I feel it would be cool for a progressbar to exist while the curation algorithm is working, because it takes so long

**Comment by p2r3** [comment]
Is this... necessary? I'm really not so sure. @PancakeTAS @soni801 thoughts?

**Comment by ArcherTheReal** [comment]
Now that i think about it, i realized that the thing is shown in your terminal and not on the cli as its automated and not run by organizers

**Comment by ArcherTheReal** [comment]
Ill close this as not planned

**Comment by rudkoLA** [comment]
does it even matter how long it takes if it's done after the leaderboard locks instead of when the map releases

**Comment by ArcherTheReal** [comment]
No i was just thinking about it as being run from the cli cause thats where i was running it from

**Comment by PancakeTAS** [comment]
Hmmmm...
My local epochtal is still curating and it has been for the past 25 minutes. Before, curation took maybe 10 sometimes 15 minutes which means this week has a bunch more maps uploaded compared to last week.
Now as far as I know, epochtal does not know how many maps there are on the workshop until it fetches the last batch of maps at which point it's already done curating.
That would make a progress bar hard to implement.

Alright, how about status updates then? Print to the console how many maps have been curated thus far to see if the algorithm is actually doing something or stuck in an infite loop.
I don't see a use for this whatsoever, there aren't even any loops that could potentially be infinite in the source code for the curation.

Now, seeing how the progress bar would likely be in the CLI and no one even has the CLI opened, I don't think this is worth implementing. There's other ways to check if the curation algorithm is doing something or not (e.g. look at task manager/htop/btop).

Don't close the issue to prematurely by the way, at least wait like 10 minutes :sob:
