### ISSUE TITLE
comments are shown incorrect

### ISSUE THREAD

**Issue by PizzaPost** [p2r3/epochtal#72]
On safari are the comments behind the toolbar.

![IMG_2939](https://github.com/user-attachments/assets/92580ec6-85ca-4147-8d1b-4e7af55096f5)
![IMG_2940](https://github.com/user-attachments/assets/8a713712-b7ff-4b5d-b530-eb559f464fc9)

**Comment by PancakeTAS** [comment]
I can't seem to replicate this?
https://github.com/user-attachments/assets/ff90b51b-3b0a-45e6-a233-d4879e0ac077
The comment is shown below and nor above the speech bubble, but thats seems intended?

**Comment by p2r3** [comment]
@PizzaPost your viewport looks zoomed in, because there's no way the leaderboard and header have zero margins horizontally. Can we confirm that's the case so this issue can be closed?

**Comment by PizzaPost** [comment]
@p2r3 its zoomed out (85%) but the fix worked.
