### ISSUE TITLE
User profile participation graph incomplete

### ISSUE THREAD

**Issue by NobodyForNothing** [p2r3/epochtal#90]
The points over time graph on [my profile](https://epochtal.p2r3.com/profile/#76561199175290487) doesn't show the last week. Data until week 137 is displayed but the latest week I participated in is 152.

![image](https://github.com/user-attachments/assets/d388c061-299c-457f-a545-bcd9cd9db179)

**Comment by p2r3** [comment]
You've got this a bit backwards. The participation graph is the incorrect one, there's an annoying timestamp issue with that, so let's let this issue be the one that tracks this.

Point is, you did not last participate on week 152. It is currently week 137. Week 152 is in the future, and that's the actual issue.
